### ISSUE TITLE
PyVISA vs PyMeasure

### ISSUE THREAD

**Issue by froufrounette** [pymeasure/pymeasure#389]
Hi all,

I am trying to read and write using PyMeasure since much of the functionalities are already available. However, when I want to write/read an instrument created in PyMeasure, I get a time out error. However, if I open my instrument by myself by using : 
rm=pyvisa.ResourceManager()
lock_in=rm.open_resource('TCPIPO:ipadress::port::SOCKET'), 
The write/read method works. 

What is wrong? And how can I use PyMeasure properly. 

Instruments:
Connecting to two Keithley 6221 and one Ametek7270 by ethernet cable.

**Comment by bilderbuchi** [comment]
Welcome!
Hm, it's hard to say at this point. Let me throw a couple of questions your way:
Do all the instruments not work? Even if you connect only one? 
What happens if, instead of the defined properties, you use the instrument.read(), .write(), .ask() methods directly, just as you do when doing it directly with pyvisa?
If that does not work, what if you use instrument.adapter.read(), .write(), .ask()?
If that does not work, what if you use instrument.adapter.connection.read(), .write(), .ask()?
Do you have settings regarding line termination characters? If yes, you can specifiy those when creating the instruments using the `read_termination` and  `write_termination` keyword arguments.

**Comment by froufrounette** [comment]
Hi, 

thank you. It was missing the read/write termination

**Comment by bilderbuchi** [comment]
So, did you solve your problem?

**Comment by froufrounette** [comment]
Yes, for now it works.

Thank you again

**Comment by bilderbuchi** [comment]
Great! You're welcome. :-)
