### ISSUE TITLE
conda-forge misses Keithley2260B

### ISSUE THREAD

**Issue by misterjay92** [pymeasure/pymeasure#425]
Hey guys,

thanks a lot for pymeasure!
I was just writing my own 2260B class and stumbled upon yours! It was added to pymeasure a month ago but sadly it cant be installed via conda. The conda-forge page also shows the last update 1 month and 27 days ago.
Would you pleeease add it or is there another elegant way of adding the class to my library? I would prefer not to copy the code......

Best regards

**Comment by bilderbuchi** [comment]
Yeah, this was merged after the latest release was cut. You can try using the [development version](https://pymeasure.readthedocs.io/en/latest/dev/contribute.html#using-the-development-version). Best in a separate conda environment, as this will use pip to pull in dependencies. 
You can mitigate that by installing all the dependencies first: `conda install --only-deps pymeasure`, then only pymeasure itself is installed via pip.

If you feel adventurous, you can try using `conda develop .` instead of `pip install -e .`, but I don't know if that will work correctly. Please report back your experience! :-)
