### ISSUE TITLE
Replace deprecated telnetlib in TelnetAdapter

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/pymeasure#668]
TelnetAdapter uses [telnetlib](https://docs.python.org/3/library/telnetlib.html) which is deprecated since Python 3.11 (see [PEP 598](https://peps.python.org/pep-0594/#telnetlib)). Python 3.12 will be last version to contain telnetlib.

It is not yet urgent, but I want to raise this issue, as I encountered it by chance.

[PEP 598](https://peps.python.org/pep-0594/#telnetlib) also offers some alternatives. Maybe Pyvisa (with TCP raw) might work as well.

**Comment by dkriegner** [comment]
As far as I can see `TelnetAdapter` is only used by the `AttocubeConsoleAdapter`. I think this could be also reimplemented using a different underlying adapter. I remember vaguely it was some convenience reason to add the TelnetAdapter since some things worked more elegantly with it. 

But if there is no easy drop in replacement and this is not otherwise widely used I think it could be just dropped and a different solution can be found for the Attocube device.
