### ISSUE TITLE
Add collection of instrument solutions to documentation

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/pymeasure#779]
@bilderbuchi proposed in #778 to add a list of solutions for instrument implementations to the documentation:
For different problems there are listed instruments, which solve these problems. 

I think the end of the file might be a good place.

**Comment by bilderbuchi** [comment]
A separate file should also be fine -- the `adding_instruments.rst` is slowly growing huge.

To mirror what's in #778, this should be a FAQ-style directory in the documentation where we record weird/special instruments, so that contributors can check their list for implementation inspiration.
I imagine something like
* TC038, x and y implement binary frame-based communication
* aja.DCXS has replies that are all the same lengths
* aja.DCXS has some garbage in the buffer after startup, that needs to be discarded
* XYZ (I forget which) VNA can dynamically configure itself depending on which hardware modules are present
* In the MKS937B, not all the channels have all capabilities
* ...

**Comment by bilderbuchi** [comment]
* `tcpowerconversion.CXN` (#800) needs overridden `values` for both the instrument and its channels, and needs to take care to use the correct `ask` method. A class-level override `values=values` can be used as long as we don't have a better solution (#811).

**Comment by bmoneke** [comment]
- #802 has different channel names on the front panel (A, B, C) and command ids (1, 2, 3).

**Comment by bmoneke** [comment]
- #827 has different Channel property attributes for different subclassed instruments.
